### ISSUE TITLE
Typo test-sytem

### ISSUE THREAD

**Issue by adelton** [stevegrubb/distro-elf-inspector#1]
The README says
```
2) run ./test-system (install dependencies if missing)
```
but that fails with
```
# ./test-system
-bash: ./test-system: No such file or directory
```

The file `test-sytem` likely needs to be renamed.

**Comment by stevegrubb** [comment]
It's in the top level directory after cloning.

**Comment by adelton** [comment]
But the name is different from the one in the README. Either the README needs to be fixed, or the file needs to be renamed.

**Comment by stevegrubb** [comment]
OK, I see. It would have been faster to fix if you mentioned the 's' was missing. Fixed now. Thanks for reporting the problem.
